baseURL = 'https://davideisinger.com/'
languageCode = 'en-us'
title = 'David Eisinger'
theme = 'v2'
enableGitInfo = true
timeout = '120s'

[params.author]
name = 'David Eisinger'
email = 'hello@davideisinger.com'

[permalinks]
pages = '/:title'

[services.rss]
limit = 10

[markup.highlight]
style = 'nord'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'blackfriday'

[security.funcs]
getenv = ['DITHER_SERVER']
