baseURL = 'https://davideisinger.com/'
languageCode = 'en-us'
title = 'David Eisinger'
theme = 'v2'
enableGitInfo = true

[permalinks]
  pages = '/:title'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'nord'
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'blackfriday'
